export enum Status {
    DRAFT = "DRAFT",
    ACTIVE = "ACTIVE",
    PENDING_EFFECTIVE = "PENDING_EFFECTIVE",
    PENDING_APPROVAL = "PENDING_APPROVAL",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    DELETED = "DELETED",

}